### ISSUE TITLE
CORS conflict even with .env API-DOMAIN

### ISSUE THREAD

**Issue by Hasan-git** [songshenzong/api#1]
i am  getting the following error ->
## ### Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource

mostly I am getting this error when I send multiple API request once

**Comment by songshenzong** [comment]
Since v1.1, You can configure this in your .env file.

SONGSHENZONG_API_CORS=true
SONGSHENZONG_API_CORS_CREDENTIALS=true
SONGSHENZONG_API_CORS_MAX_AGE=86400
Important: If you do not set SONGSHENZONG_API_CORS up, the Songshenzong API will use true, true, 86400.
